clc;close all;clear all;
subcarrierSpacing=60;
NRB=100;
kSSB=0;
NStart=0;
NCRBSSB = 19;
NCellID=17;
carrierFrequency = 4e9;

mib=struct();
mib.SFN=10;
mib.subCarrierSpacingCommon=nrCom.SCSCommon.scs15or60;
mib.dmrsTypeAPosition=nrCom.DmrsTypeAPosition.pos2;
mib.pdcch_ConfigSIB1=254;
mib.cellBarred=nrCom.CellBared.notBarred;
mib.intraFreqReselection=nrCom.IntraFreqReselection.notAllowed;
[rg,dbg]=createFrame( ...
    round(log2(15/15)), ...
    NRB, ...
    kSSB, ...
    NStart, ...
    NCRBSSB,...
    NCellID, ...
    ones(1,8), ...
    'A', ...
    carrierFrequency,...
    mib, ...
    0);
waveform=ofdmModulator(rg,NStart,round(log2(15/15)),false);
save("waveform.mat","waveform")